### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by miked0004**
Basic Docker wrapper of json2hcl.

### CODE REVIEW

**Comment by miked0004** [comment]
I require no attribution. Just adding this because I found it useful. Feel free to grab the Dockerfile and reject the PR, if you find it useful.

**Comment by kvz** [comment]
I wonder why this is useful when you can have a go binary for every platform without containerizing it? Honest question this!

**Comment by Acconut** [comment]
> why this is useful when you can have a go binary for every platform without containerizing it?

I assume that you can run the binary from source code but don't have to install Go? But that's just a guess.

**Comment by miked0004** [comment]
Ok, thanks for the consideration. Just an offer.

**Comment by kvz** [comment]
I guess we don’t auto build cross platform binaries for releases like we do for tusd. But if we set that up, what would the purpose for docker be for a cli tool @acconut?

**Comment by Acconut** [comment]
We do build cross platform binaries for all common platform already, for ever release. For example: https://github.com/kvz/json2hcl/releases/tag/v0.0.6

**Comment by kvz** [comment]
I see, so that circles us back to the question, why would docker be useful for cli tools if you already had binaries available for each platform. Serious question. I guess containing memory usage or privileges might be easy/er with it. Yes, I guess you could be sure it could not temper with files in your home dir unless you explicitly mapped volumes?

**Comment by Acconut** [comment]
As I said above my thought is that you can build it from source (no untrusted binary to download) without install Go, which is not the easiest installation process. But that's just a guess.

**Comment by kvz** [comment]
Ah right, to run the sources directly, missed that part sorry! 👌

**Pull request closed without merging**
